#!/bin/bash

export JEKYLL_VERSION=3.8
docker run --rm \
  --volume="$PWD/src:/srv/jekyll" \
  --volume="$PWD/src/vendor/bundle:/usr/local/bundle" \
  -it jekyll/builder:$JEKYLL_VERSION \
  jekyll build
